name: Generate AFL RSS Feed

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main  # Run on pushes to main branch

jobs:
  generate-feed:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate RSS feed
      run: python src/main.py
      
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Commit and push if feed changed
      run: |
        git add feed.xml previously_scraped.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update RSS feed" && git push) 